<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_news_imgpreviewonly"
 *
 * Auto generated by Extension Builder 2015-06-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Image preview only for EXT:news',
	'description' => 'Adds a checkbox to EXT:news images to display image only as preview.',
	'category' => 'plugin',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'news' => '3.2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);